#!/usr/bin/env python

import os

env = Environment(ENV=os.environ, PDFLATEX="lualatex",
                  tools=["default", "dtxtools"] )

root = "kprussing"
pdf = env.PDF("kprussing.dtx",
              MAKEINDEX=env["MAKEINDEX"] + " -s gind.ist")
stys = env.ins2sty([], "kprussing.ins")
Depends(pdf, stys)
if not GetOption("clean"):
    Default(pdf)

Export("env stys")
SConscript( os.path.join("examples", "SConscript") )

