" Only use vim not vi
set nocompatible

" Do I really want to disable this?  Otherwise, I can't use this to
" syntax highlight non-standard files.
"set modelines=0

" I want to see the line number and I like the 72 characters on a line
set number
set textwidth=72
if exists('+colorcolumn')
    set colorcolumn=73
endif

" Initialize pathogen
filetype off
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect('bundle/{}')
call pathogen#helptags()

" Detect file types and auto indent
filetype plugin indent on

" Set the color scheme here. zenburn for now!
syntax enable
"set background=dark
set t_Co=256
"if has("win32") || has("win32unix")
colorscheme zenburn
"endif

" And set a sane font for gVim
if has("gui_running")
    if has("win32")
        set guifont=Consolas:h11:cANSI
    elseif has("mac")
        set guifont=Monaco:h11
    endif
    set guioptions=
endif

" I like syntax highlighting and spelling on
set spell
set spellfile=$HOME/.vim/dictionary.add

" And of course these are my tab preferences
set autoindent      " Indent intelligently
set expandtab       " Tabs are spaces
set shiftwidth=4    " Indents are 4 spaces
set tabstop=4       " Indent every 4 spaces
set softtabstop=4   " Backspace deletes tabs

set nowrap                      " Don't wrap the lines. It's ugly
set encoding=utf-8              " Encode as UTF-8
set scrolloff=3                 " Number of line to keep around cursor
set showmode                    " Show the mode
set showcmd                     " Show partial command
set hidden                      " Hide a buffer instead of abandoning
set wildmenu                    " Show list instead of completing
set wildmode=list:longest       " Tab complete longest common part
set visualbell                  " Use a visual bell instead of beeping
set ttyfast                     " Makes redraw fast. Smooths typing
set ruler                       " Turn on the ruler
set backspace=indent,eol,start  " Delete like a real program
set laststatus=2

" Ignore some common file extensions for autocomplete.
set wildignore+=*.pyc,*.o,                          " Object code
set wildignore+=*.png,*.pdf_tex,*.pgf               " Generated images.

" Ignore some LaTeX files
set wildignore+=*.aux,*.pdf,*.png,*.bbl,*.blg,*.fls,*.log,*.nav,*.out
set wildignore+=*.svn,*.toc,*.snm,*.sta,*.fdb_latexmk

" Now make myself learn to use the correct keys
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>
"vnoremap <up> <nop>
"vnoremap <down> <nop>
"vnoremap <left> <nop>
"vnoremap <right> <nop>

" Maps for easier buffer switching.  This is analogous to window
" changing in tmux.
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bNext<CR>

" This remap will probably help me out a lot...
let mapleader = ","

"nnoremap / /\v
"vnoremap / /\v

set ignorecase  " Case insensitive search
set smartcase   " Case sensitive when upper case present
set incsearch   " Search while typing
set showmatch   " Show matching brackets
set hlsearch    " Highlight search

" Clear search highlighting
nnoremap <leader><space> :noh<cr>

" And remap keys for easy windowing
nnoremap <leader>w <C-w>v<C-w>l

" Quickly save a session in the current directory.  This is mainly for
" pausing my work in a development directory.
nnoremap <leader>s :mksession!<CR>

" Use a login shell with the GUI
if has("gui_running")
    set shellcmdflag=-ic
endif

"--------1---------2---------3---------4---------5---------6---------7--
" The function to create and set the backup directories for cleanliness
function! InitializeDirectories()
    let separator = "."
    let parent = $HOME
    let prefix = '.vim'
    let dir_list = {
        \ 'backup': 'backupdir',
        \ 'views': 'viewdir',
        \ 'undo' : 'undodir',
        \ 'swap': 'directory' }
    for [dirname, settingname] in items(dir_list)
        let directory = parent . '/' . prefix . '/' . dirname . '/'
        if exists("*mkdir")
            if !isdirectory(directory)
                call mkdir(directory)
            endif
        endif
        if !isdirectory(directory)
            echo "Warning: unable to create directory: " . directory
            echo "Try: mkdir -p " .directory
        else
            let directory = substitute(directory, " ", "\\\\ ", "")
            exec "set " . settingname . "=" . directory
        endif
    endfor
endfunction
call InitializeDirectories()
set undofile

"--------1---------2---------3---------4---------5---------6---------7--
" Some abbreviations for sectioning code.
ab #f !--------1---------2---------3---------4---------5---------6---------7--
ab #c //-------1---------2---------3---------4---------5---------6---------7--
ab #m %--------1---------2---------3---------4---------5---------6---------7--
ab #p #--------1---------2---------3---------4---------5---------6---------7--

let g:tex_flavor = "latex"
