#!/usr/bin/env python
__doc__="""
A wrapper to debug a module run as a script.

A wrapper script to launch IPython and start a debugging session on a
module run as a script.  The first argument is module that would
normally be run by calling ``python -m somepackage.somemodule``.  All
subsequent arguments are passed to the module. 

"""

if __name__ == "__main__":
    import argparse, pdb, runpy, sys
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
            "module", help="The module to execute"
        )
    parser.add_argument(
            "args", help="Arguments to module", nargs=argparse.REMAINDER
        )
    args = parser.parse_args()
    print(args.args)
    sys.argv = args.args
    pdb.runcall(
            runpy.run_module, args.module, run_name="__main__"
        )
# end if

