#!/usr/bin/env python
__doc__="""
Compute the arithmetic mean of a set of numbers.
"""
import argparse
import sys

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument( \
            "N", nargs="+", type=float, help="Values to average" \
        )
    args = parser.parse_args()
    print(sum(args.N) /len(args.N))
# end if

